"""
Mandatory JSON Schemas for Agent Injection.
These strings are appended to the creative system prompts generated by the frontend.
They enforce a strict JSON contract for the OrchestratorEngine.
"""

DIRECTOR_SCHEMA_INJECTION = """
!!! MANDATORY OUTPUT FORMAT !!!
You MUST return your response as a strict JSON object. No markdown blocks, no conversational text before or after the JSON.
Your JSON must strictly follow this structure:
{
  "scaffold_plan": [
    {
      "chunk_instruction": "Instructions for the writer for this act.",
      "chunk_summary_hook": "Summary of what happens in this chunk.",
      "pacing_directive": "One of: frenetic_action, slow_monologue, dialogue_ping_pong, suspense_build, or emotional_reveal",
      "target_word_count_estimate": 250
    }
  ],
  "cinematic_music_prompt": "Prompt for the SoundEngine. Ex: 'Dark synthwave tense loop, deep bass, 80 BPM, without vocals'"
}
"""

WRITER_SCHEMA_INJECTION = """
!!! MANDATORY OUTPUT FORMAT !!!
You MUST return your response as a strict JSON object. No markdown blocks.
Your JSON must strictly follow this structure:
{
  "text": "The actual written script/narrative text for the current act.",
  "continuation_required": true or false
}
"""

CRITIC_SCHEMA_INJECTION = """
!!! MANDATORY OUTPUT FORMAT !!!
You MUST return your response as a strict JSON object. No markdown blocks.
Your JSON must strictly follow this structure:
{
  "decision": "pass", "revise" or "reject",
  "feedback": "Structural mechanical analysis of the text.",
  "revised_chunk_if_revise": "If decision is 'revise', output the newly revised text here. Otherwise null."
}
"""

ARCHIVIST_SCHEMA_INJECTION = """
!!! MANDATORY OUTPUT FORMAT !!!
You MUST return your response as a strict JSON object. No markdown blocks.
Your JSON must strictly follow this structure:
{
  "current_location": "...",
  "character_statuses": [{"name": "...", "status": "..."}],
  "last_concrete_action": "...",
  "requires_continuation": true or false
}
"""

ARTIST_SCHEMA_INJECTION = """
!!! MANDATORY OUTPUT FORMAT !!!
You MUST return your response as a strict JSON array of objects. No markdown blocks.
Each object must represent a visual prompt for an image generation pipeline.
Your JSON must strictly follow this structure:
[
  {
    "act": "thumbnail",
    "prompt": "Visual description in English for the image generator..."
  },
  {
    "act": "act_1",
    "prompt": "Visual description in English for act 1..."
  }
]
"""
