"""
Mandatory JSON Schemas for Agent Injection.
These strings are appended to the creative system prompts generated by the frontend.
They enforce a strict JSON contract for the OrchestratorEngine.
"""

DIRECTOR_SCHEMA_INJECTION = """
!!! MANDATORY OUTPUT FORMAT !!!
You MUST return your response as a strict JSON object. No markdown blocks, no conversational text before or after the JSON.
Your JSON must strictly follow this structure:
{
  "scaffold_plan": [
    {
      "act_number": 1,
      "chunk_instruction": "Instructions for the writer for this act.",
      "chunk_summary_hook": "Summary of what happens in this chunk.",
      "pacing_directive": "One of: frenetic_action, slow_monologue, dialogue_ping_pong, suspense_build, or emotional_reveal"
    }
  ],
  "cinematic_music_prompt": "General vibe of the soundtrack requested for the entire project."
}
"""

WRITER_SCHEMA_INJECTION = """
!!! MANDATORY OUTPUT FORMAT !!!
You MUST return your response as a strict JSON object. No markdown blocks.
Your JSON must strictly follow this structure:
{
  "acts": [
    {
      "act_number": 1,
      "text": "The actual creative narrative text written for this act."
    }
  ]
}
"""

CRITIC_SCHEMA_INJECTION = """
!!! MANDATORY OUTPUT FORMAT !!!
You MUST return your response as a strict JSON object. No markdown blocks.
Your JSON must strictly follow this structure:
{
  "decision": "pass" | "revise",
  "feedback": "Structural mechanical analysis, finding logic errors, AI cliches, or grammar issues across the entire story.",
  "revised_acts": [
    {
      "act_number": 1,
      "text": "If decision is 'revise', output the newly revised text for this act here. Keep original if no revision needed."
    }
  ]
}
"""

AUDIENCE_SCHEMA_INJECTION = """
!!! MANDATORY OUTPUT FORMAT !!!
You MUST return your response as a strict JSON object. No markdown blocks.
Your JSON must strictly follow this structure:
{
  "decision": "pass" | "reject",
  "feedback": "Subjective review: does this engage the target audience? Does it have hooks? If rejecting, explain why."
}
"""

ARCHIVIST_SCHEMA_INJECTION = """
!!! MANDATORY OUTPUT FORMAT !!!
You MUST return your response as a strict JSON object. No markdown blocks.
Your JSON must strictly follow this structure:
{
  "current_location": "Description of the physical location of this act",
  "character_statuses": [{"name": "...", "appearance": "...", "status": "..."}],
  "concrete_actions_in_act": "Summary of what physically happened"
}
"""

ARTIST_SCHEMA_INJECTION = """
!!! MANDATORY OUTPUT FORMAT !!!
You MUST return your response as a strict JSON object. No markdown blocks.
Your JSON must strictly follow this structure:
{
  "positive_prompt": "Visual description in English for ComfyUI. Must include location and character appearance from the Archivist state.",
  "negative_prompt": "What NOT to render in the image (e.g. text, watermark, mutated hands)."
}
"""

COMPOSER_SCHEMA_INJECTION = """
!!! MANDATORY OUTPUT FORMAT !!!
You MUST return your response as a strict JSON object. No markdown blocks.
Your JSON must strictly follow this structure:
{
  "ace_prompt": "Prompt for ACE-Step-1.5XL describing instruments, tempo, and mood.",
  "lyrics": "Generated lyrics for this section, if vocal mode is enabled. Otherwise null."
}
"""
